export type Block =
  | { type: "p"; text: string }
  | { type: "h2"; text: string }
  | { type: "ul"; items: string[] };

export interface BlogPost {
  slug: string;
  title: string; // <title> / H1
  description: string; // meta description + card excerpt
  date: string; // ISO date
  readingMinutes: number;
  body: Block[];
  related: string[]; // tool slugs to link
}

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "how-to-get-youtube-video-transcript",
    title: "How to Get a Transcript from Any YouTube Video (2026 Guide)",
    description:
      "Three reliable ways to get the full transcript of a YouTube video — including the fastest method that takes about ten seconds and works on any device.",
    date: "2026-06-25",
    readingMinutes: 5,
    body: [
      {
        type: "p",
        text: "If you have ever needed the exact words from a YouTube video — to quote a source, study a lecture, or turn a talk into an article — you already know that watching the whole thing and typing notes is painfully slow. The good news is that most YouTube videos already have a transcript hidden behind the scenes, and there are a few easy ways to pull it out. This guide walks through the three most reliable methods and when to use each.",
      },
      {
        type: "h2",
        text: "Method 1: Paste the link into a transcript tool (fastest)",
      },
      {
        type: "p",
        text: "The quickest way is to use a dedicated transcript tool. You copy the video's URL, paste it in, and the full transcript appears in a few seconds — already cleaned up and ready to read. This is the method most people want because it requires no account, works the same on a phone or laptop, and gives you the text with clickable timestamps so you can jump straight to any moment in the video.",
      },
      {
        type: "p",
        text: "With LinkTranscript, the flow is: copy the YouTube link, paste it into the box on the homepage, and click Get Transcript. From there you can toggle timestamps on or off, search within the transcript, copy it with one click, or export it as TXT, Markdown, SRT, or VTT. It is the same idea as the built-in method below, but faster and with export options built in.",
      },
      {
        type: "h2",
        text: "Method 2: Use YouTube's built-in transcript panel",
      },
      {
        type: "p",
        text: "YouTube has a transcript feature built into the desktop site, though it is a little buried. Open the video, click the three-dot menu (or the \"...more\" link under the title), and choose \"Show transcript.\" A panel opens on the right with the timestamped text. You can turn the timestamps off from the panel's menu and then select and copy the text manually.",
      },
      {
        type: "ul",
        items: [
          "Pros: no third-party tools, always available on desktop.",
          "Cons: only on desktop (not the mobile app), no export formats, and copying long transcripts cleanly is fiddly because line breaks and timestamps come along for the ride.",
        ],
      },
      {
        type: "h2",
        text: "Method 3: Download captions as a subtitle file",
      },
      {
        type: "p",
        text: "If you specifically need a subtitle file for a video editor, you can export captions as SRT or VTT. A transcript tool can generate these directly from a link, which is usually easier than hunting through download utilities. SRT and VTT both carry precise start and end times for each line, which is exactly what editors and web players expect.",
      },
      {
        type: "h2",
        text: "What if the video has no transcript?",
      },
      {
        type: "p",
        text: "Not every video can be transcribed. A transcript only exists if the video has captions — either uploaded by the creator or auto-generated by YouTube. Most popular videos have at least auto-generated captions, but some do not, and private, deleted, or region-blocked videos cannot be accessed at all. If a tool tells you there is no transcript available, that usually means the video genuinely has no captions to pull from.",
      },
      {
        type: "h2",
        text: "A note on accuracy",
      },
      {
        type: "p",
        text: "Creator-uploaded captions are typically very accurate, including punctuation and proper names. Auto-generated captions are good but not perfect — they can miss punctuation or misread unusual words. Whichever you get, it is worth a quick proofread before you publish or cite anything important. Clickable timestamps make this easy: jump to the moment in question and confirm the wording against the audio.",
      },
      {
        type: "p",
        text: "For most people, pasting the link into a transcript tool is the best balance of speed and flexibility. Try it with any video and you will have clean, exportable text in about the time it took to read this paragraph.",
      },
    ],
    related: [
      "youtube-transcript-generator",
      "youtube-to-text",
      "youtube-transcript-download",
    ],
  },
  {
    slug: "ways-to-use-youtube-transcripts",
    title: "10 Smart Ways to Use YouTube Transcripts",
    description:
      "Transcripts are not just for accessibility. Here are ten practical ways students, researchers, and creators turn a video's words into something more useful.",
    date: "2026-06-25",
    readingMinutes: 6,
    body: [
      {
        type: "p",
        text: "A transcript turns a video — something you can only consume in real time — into text you can search, skim, quote, and repurpose. Once you have the words on the page, a lot of slow tasks become fast. Here are ten of the most useful things people do with a YouTube transcript.",
      },
      {
        type: "h2",
        text: "1. Skim a long video in a fraction of the time",
      },
      {
        type: "p",
        text: "Reading is far faster than watching. A 40-minute talk might take five minutes to skim as text. You can scan for the part you actually care about instead of dragging the playhead around hoping to land on it.",
      },
      {
        type: "h2",
        text: "2. Quote a source accurately",
      },
      {
        type: "p",
        text: "Researchers and journalists need exact wording. A transcript gives you the precise quote, and clickable timestamps let you verify it against the audio before you publish.",
      },
      {
        type: "h2",
        text: "3. Turn a lecture into study notes",
      },
      {
        type: "p",
        text: "Students can pull the transcript of a lecture, search it for key terms, and build notes or a study guide without rewatching. Exporting to Markdown drops it straight into Notion or Obsidian.",
      },
      {
        type: "h2",
        text: "4. Write a blog post from a video",
      },
      {
        type: "p",
        text: "Creators can repurpose a talk, interview, or tutorial into a written article. The transcript is the raw material — the quotes, the structure, the key points — so the first draft writes itself.",
      },
      {
        type: "h2",
        text: "5. Draft social posts",
      },
      {
        type: "p",
        text: "One good insight from a video can become a LinkedIn post or an X thread. Pull the transcript, find the standout line, and build a post around it.",
      },
      {
        type: "h2",
        text: "6. Translate the content",
      },
      {
        type: "p",
        text: "Text is far easier to translate than audio. Once you have the transcript, you can run it through your translation tool of choice to make the content accessible in other languages.",
      },
      {
        type: "h2",
        text: "7. Make the content searchable",
      },
      {
        type: "p",
        text: "Video is a black box to search engines and to you. A transcript makes every word findable — search across a long interview for the one statistic you remember hearing.",
      },
      {
        type: "h2",
        text: "8. Create subtitles for your own edits",
      },
      {
        type: "p",
        text: "If you are editing clips, exporting the transcript as SRT or VTT gives you subtitle files with accurate timing, ready to drop into your editor or web player.",
      },
      {
        type: "h2",
        text: "9. Feed it to an AI assistant",
      },
      {
        type: "p",
        text: "Paste a clean transcript into your favorite AI tool and ask for a summary, bullet notes, key takeaways, or an outline. Because you control the prompt, you decide exactly what you get back.",
      },
      {
        type: "h2",
        text: "10. Extract action items from meetings or webinars",
      },
      {
        type: "p",
        text: "Recorded calls and webinars are full of decisions and to-dos buried in the conversation. A transcript lets you scan for the commitments and pull them into a checklist.",
      },
      {
        type: "p",
        text: "The common thread: a transcript is leverage. The video stays the same, but the text version multiplies what you can do with it. Grab a transcript from any video and pick the use case that fits your day.",
      },
    ],
    related: [
      "youtube-transcript-to-notes",
      "transcript-to-blog-post",
      "youtube-video-summary",
    ],
  },
  {
    slug: "transcript-vs-captions-vs-subtitles",
    title: "Transcripts vs. Captions vs. Subtitles: What's the Difference?",
    description:
      "Transcript, captions, subtitles, SRT, VTT — the terms get mixed up constantly. Here's a plain-English breakdown of what each one actually means.",
    date: "2026-06-25",
    readingMinutes: 4,
    body: [
      {
        type: "p",
        text: "Transcript, captions, subtitles, SRT, VTT — these words get used interchangeably, but they are not the same thing. Knowing the difference helps you ask for the right output and pick the right export format. Here is the plain-English version.",
      },
      {
        type: "h2",
        text: "Transcript",
      },
      {
        type: "p",
        text: "A transcript is the full text of what is said in a video or audio recording. In its simplest form it is just the words, often as continuous prose. A transcript may or may not include timestamps. It is meant to be read on its own, separate from the video — think of it like the script of what was spoken.",
      },
      {
        type: "h2",
        text: "Captions",
      },
      {
        type: "p",
        text: "Captions are text synced to the video, designed primarily for viewers who are deaf or hard of hearing. Because of that, true \"closed captions\" often include non-speech information like [music playing] or [applause]. Captions assume the viewer cannot hear the audio, so they aim to convey everything meaningful on the soundtrack, not just the dialogue.",
      },
      {
        type: "h2",
        text: "Subtitles",
      },
      {
        type: "p",
        text: "Subtitles are also text synced to the video, but they traditionally assume the viewer can hear the audio and mainly need the words — often a translation into another language. In everyday use, especially on YouTube, \"subtitles\" and \"captions\" are used almost interchangeably, but the technical distinction is that subtitles focus on dialogue while captions cover all audio.",
      },
      {
        type: "h2",
        text: "SRT and VTT: the file formats",
      },
      {
        type: "p",
        text: "SRT (SubRip) and VTT (WebVTT) are not types of text — they are file formats for storing timed captions or subtitles. Each entry has a start time, an end time, and a line of text. SRT is the long-standing standard supported by virtually every video editor. VTT is the web-native format used by HTML5 video players and supports a bit more styling. If an editor or player asks for a subtitle file, it almost always wants one of these two.",
      },
      {
        type: "ul",
        items: [
          "Transcript → the words, for reading (TXT or Markdown).",
          "Captions/subtitles → timed text overlaid on video.",
          "SRT / VTT → the file formats that hold timed text.",
        ],
      },
      {
        type: "h2",
        text: "Which one do you actually need?",
      },
      {
        type: "p",
        text: "If you want to read, quote, search, or repurpose what was said, you want a transcript — export it as TXT or Markdown. If you are editing video or adding captions to a player, you want a subtitle file — export SRT or VTT. The convenient part is that a good transcript tool can produce all of these from the same video, so you do not have to choose up front.",
      },
    ],
    related: ["srt-to-txt", "vtt-to-txt", "video-to-markdown"],
  },
];

export function getBlogPost(slug: string): BlogPost | undefined {
  return BLOG_POSTS.find((p) => p.slug === slug);
}
