/** Shared types used across the extraction service, API routes, and UI. */

export interface TranscriptSegment {
  /** Start time in seconds. */
  start: number;
  /** Duration in seconds. */
  duration: number;
  /** Cleaned caption text for this segment. */
  text: string;
}

export interface CaptionTrack {
  /** BCP-47 language code, e.g. "en", "es". */
  languageCode: string;
  /** Human-readable language name, e.g. "English". */
  label: string;
  /** Whether the track is auto-generated (ASR). */
  autoGenerated: boolean;
}

export interface VideoMeta {
  videoId: string;
  title: string;
  author?: string;
  thumbnail?: string;
  sourceUrl: string;
  durationSeconds?: number;
}

export interface TranscriptResult {
  meta: VideoMeta;
  language: string;
  /** All caption tracks available for the video (for the language selector). */
  availableTracks: CaptionTrack[];
  segments: TranscriptSegment[];
  /** Convenience aggregates computed server-side. */
  wordCount: number;
  charCount: number;
  /** Estimated reading time in minutes (rounded up, min 1). */
  readingTimeMinutes: number;
  /** ISO timestamp of when the transcript was generated. */
  generatedAt: string;
}

/** Error codes mapped to friendly, user-facing messages. */
export type TranscriptErrorCode =
  | "INVALID_URL"
  | "NO_TRANSCRIPT"
  | "VIDEO_UNAVAILABLE"
  | "AGE_RESTRICTED"
  | "RATE_LIMITED"
  | "FETCH_FAILED"
  | "UNKNOWN";

export class TranscriptError extends Error {
  code: TranscriptErrorCode;
  status: number;
  constructor(code: TranscriptErrorCode, message: string, status = 400) {
    super(message);
    this.code = code;
    this.status = status;
    this.name = "TranscriptError";
  }
}

export const FRIENDLY_ERRORS: Record<TranscriptErrorCode, string> = {
  INVALID_URL:
    "That doesn't look like a valid YouTube URL. Paste a link like https://www.youtube.com/watch?v=…",
  NO_TRANSCRIPT:
    "This video doesn't have captions available, so there's no transcript to extract.",
  VIDEO_UNAVAILABLE:
    "This video is private, deleted, or otherwise unavailable. Try a different link.",
  AGE_RESTRICTED:
    "This video is age-restricted and its captions can't be accessed without sign-in.",
  RATE_LIMITED:
    "We're being rate-limited by YouTube right now. Please wait a moment and try again.",
  FETCH_FAILED:
    "We couldn't reach YouTube to fetch this transcript. Please try again shortly.",
  UNKNOWN: "Something went wrong fetching the transcript. Please try again.",
};

export type AiTransformType =
  | "summary"
  | "bullet_notes"
  | "key_takeaways"
  | "blog_post"
  | "linkedin_post"
  | "x_thread"
  | "study_guide"
  | "meeting_notes"
  | "action_items"
  | "custom";

export type ExportFormat = "txt" | "md" | "srt" | "vtt";
