import { config } from "@/lib/config";
import {
  TranscriptError,
  TranscriptResult,
  TranscriptSegment,
} from "@/lib/types";
import { extractVideoId, thumbnailUrl, watchUrl } from "./url";

/**
 * Hosted provider: TranscriptAPI (https://transcriptapi.com).
 *
 * Used when TRANSCRIPTAPI_KEY is set. TranscriptAPI runs the residential-proxy
 * infrastructure that lets caption fetching work from cloud hosts (Vercel),
 * where direct YouTube requests are blocked.
 *
 * Endpoint:
 *   GET /transcript?video_url=...&format=json&include_timestamp=true&send_metadata=true
 *   Authorization: Bearer <key>
 * Response:
 *   { video_id, language, transcript: [{ text, start, duration }],
 *     metadata: { title, author_name, author_url, thumbnail_url } }
 */

interface ApiSegment {
  text?: string;
  start?: number;
  duration?: number;
}

interface ApiResponse {
  video_id?: string;
  language?: string;
  transcript?: ApiSegment[] | string;
  metadata?: {
    title?: string;
    author_name?: string;
    author_url?: string;
    thumbnail_url?: string;
  };
}

export async function getTranscriptViaApi(
  input: string,
): Promise<TranscriptResult> {
  const videoId = extractVideoId(input); // validates the URL up front

  const url =
    `${config.transcriptApi.baseUrl}/transcript` +
    `?video_url=${encodeURIComponent(input)}` +
    `&format=json&include_timestamp=true&send_metadata=true`;

  let res: Response;
  try {
    res = await fetch(url, {
      headers: { Authorization: `Bearer ${config.transcriptApi.key}` },
      cache: "no-store",
    });
  } catch {
    throw new TranscriptError(
      "FETCH_FAILED",
      "Could not reach the transcript provider.",
      502,
    );
  }

  if (!res.ok) throw mapError(res.status);

  const data = (await res.json()) as ApiResponse;
  const raw = data.transcript;
  const rawSegments: ApiSegment[] = Array.isArray(raw)
    ? raw
    : typeof raw === "string"
      ? [{ text: raw, start: 0, duration: 0 }]
      : [];

  const segments: TranscriptSegment[] = rawSegments
    .map((s) => ({
      start: typeof s.start === "number" ? s.start : 0,
      duration: typeof s.duration === "number" ? s.duration : 0,
      text: (s.text || "").replace(/\s+/g, " ").trim(),
    }))
    .filter((s) => s.text.length > 0);

  if (segments.length === 0) {
    throw new TranscriptError(
      "NO_TRANSCRIPT",
      "No transcript available for this video.",
      404,
    );
  }

  const meta = data.metadata || {};
  const language = data.language || "en";
  const text = segments.map((s) => s.text).join(" ");
  const wordCount = text.split(/\s+/).filter(Boolean).length;

  return {
    meta: {
      videoId,
      title: meta.title || "Untitled video",
      author: meta.author_name,
      thumbnail: meta.thumbnail_url || thumbnailUrl(videoId),
      sourceUrl: watchUrl(videoId),
    },
    language,
    // The API returns a single resolved track; expose it for the selector.
    availableTracks: [
      { languageCode: language, label: language.toUpperCase(), autoGenerated: false },
    ],
    segments,
    wordCount,
    charCount: text.length,
    readingTimeMinutes: Math.max(1, Math.ceil(wordCount / 200)),
    generatedAt: new Date().toISOString(),
  };
}

function mapError(status: number): TranscriptError {
  switch (status) {
    case 401:
    case 403:
      // Misconfigured/invalid key — surface as a generic fetch failure to users.
      return new TranscriptError(
        "FETCH_FAILED",
        "Transcript provider rejected the API key.",
        502,
      );
    case 402:
      // Out of credits / quota.
      return new TranscriptError(
        "RATE_LIMITED",
        "Transcript provider quota reached.",
        429,
      );
    case 404:
      return new TranscriptError(
        "NO_TRANSCRIPT",
        "No transcript available for this video.",
        404,
      );
    case 429:
      return new TranscriptError("RATE_LIMITED", "Provider rate limit.", 429);
    default:
      return new TranscriptError(
        "FETCH_FAILED",
        `Transcript provider error (${status}).`,
        502,
      );
  }
}
