import { TranscriptInput } from "@/components/TranscriptInput";
import { AdSlot } from "@/components/AdSlot";
import { Faq } from "@/components/Faq";
import {
  ExportFormats,
  FeatureGrid,
  HowItWorks,
  TrustBar,
  UseCases,
} from "@/components/marketing";

const faqs = [
  {
    q: "Is LinkTranscript free to use?",
    a: "Yes. Single transcripts are free and require no signup. Paste a link, get the transcript, and export it instantly.",
  },
  {
    q: "Which videos work?",
    a: "Any public YouTube video that has captions — either uploaded by the creator or auto-generated by YouTube. Private, deleted, or caption-free videos can't be transcribed.",
  },
  {
    q: "Do you store my transcripts?",
    a: "No. In this version transcripts are generated on demand and not stored permanently. Saved history is an optional feature coming later.",
  },
  {
    q: "Can I get a transcript in another language?",
    a: "If a video has multiple caption tracks, you can pick the language on the result page.",
  },
  {
    q: "Is this a video downloader?",
    a: "No. LinkTranscript is a transcript and notes utility. It extracts captions and text — it does not download or rehost video files.",
  },
];

export default function HomePage() {
  return (
    <>
      {/* Hero */}
      <section id="tool" className="container-px pt-16 pb-10 sm:pt-24">
        <div className="mx-auto max-w-3xl text-center">
          <span className="chip">Transcripts · Notes · Summaries</span>
          <h1 className="mt-5 text-4xl font-bold tracking-tight sm:text-5xl">
            Paste a video. Get the transcript.
          </h1>
          <p className="mx-auto mt-4 max-w-2xl text-lg text-neutral-600">
            Turn YouTube videos into clean transcripts, notes, summaries, and
            exportable text in seconds.
          </p>
        </div>
        <div className="mx-auto mt-8 max-w-2xl">
          <TranscriptInput autoFocus />
        </div>
      </section>

      <TrustBar />

      <div className="container-px py-8">
        <AdSlot slot="home-hero" />
      </div>

      <HowItWorks />
      <FeatureGrid />
      <UseCases />
      <ExportFormats />
      <Faq items={faqs} />

      {/* Bottom CTA */}
      <section className="container-px pb-20">
        <div className="card bg-accent-soft p-10 text-center">
          <h2 className="text-2xl font-semibold sm:text-3xl">
            Ready to transcribe a video?
          </h2>
          <p className="mx-auto mt-3 max-w-xl text-neutral-600">
            Paste a YouTube link and get a clean, exportable transcript in
            seconds.
          </p>
          <div className="mx-auto mt-6 max-w-xl">
            <TranscriptInput compact />
          </div>
        </div>
      </section>
    </>
  );
}
