import { TranscriptInput } from "@/components/TranscriptInput";
import { AdSlot } from "@/components/AdSlot";
import { Faq } from "@/components/Faq";
import { ConsolePreview } from "@/components/ConsolePreview";
import { InstallCta } from "@/components/InstallCta";
import {
  ExportFormats,
  FeatureGrid,
  HowItWorks,
  TrustBar,
  UseCases,
} from "@/components/marketing";

const faqs = [
  {
    q: "Is LinkTranscript free to use?",
    a: "Yes. Transcripts are free and require no signup. Paste a link, get the transcript, and export it instantly.",
  },
  {
    q: "Which videos work?",
    a: "Any public YouTube video that has captions — either uploaded by the creator or auto-generated by YouTube. Private, deleted, or caption-free videos can't be transcribed.",
  },
  {
    q: "Do you store my transcripts?",
    a: "No. Transcripts are generated on demand and not stored permanently. Saved history is an optional feature for later.",
  },
  {
    q: "Can I get a transcript in another language?",
    a: "If a video has multiple caption tracks, you can pick the language on the result page.",
  },
  {
    q: "What can I export?",
    a: "Copy the transcript with or without timestamps, or export it as TXT, Markdown, SRT, or VTT.",
  },
];

export default function HomePage() {
  return (
    <>
      {/* Hero */}
      <section id="tool" className="container-px pt-12 pb-10 sm:pt-16">
        <div className="grid items-center gap-10 lg:grid-cols-2">
          {/* Copy + input (first on mobile, so the input stays above the fold) */}
          <div>
            <span className="mono text-xs uppercase tracking-widest text-accent">
              Free YouTube transcript tool
            </span>
            <h1 className="mt-4 text-3xl font-bold tracking-tight sm:text-5xl">
              Free YouTube Transcript Generator
            </h1>
            <p className="mt-4 text-lg text-muted">
              Paste the link. Get the transcript.
            </p>
            <p className="mt-2 text-sm text-muted">
              No signup required. Export TXT, MD, SRT, or VTT.
            </p>
            <div className="mt-6">
              <TranscriptInput autoFocus />
            </div>
            <div className="mt-4">
              <InstallCta />
            </div>
          </div>

          {/* Console preview */}
          <ConsolePreview />
        </div>
      </section>

      <TrustBar />

      <div className="container-px py-8">
        <AdSlot slot="home-hero" />
      </div>

      <HowItWorks />
      <FeatureGrid />
      <UseCases />
      <ExportFormats />
      <Faq items={faqs} />

      {/* Bottom CTA */}
      <section className="container-px pb-20">
        <div className="card bg-accent-soft p-10 text-center">
          <h2 className="text-2xl font-semibold sm:text-3xl">
            Paste the link. Get the transcript.
          </h2>
          <p className="mx-auto mt-3 max-w-xl text-muted">
            Free, no signup. Copy clean text or export TXT, MD, SRT, or VTT.
          </p>
          <div className="mx-auto mt-6 max-w-xl">
            <TranscriptInput compact />
          </div>
        </div>
      </section>
    </>
  );
}
